version: "3.9"

services:
  node:
    networks:
      - backend
    build:
      context: .
      dockerfile: ./etc/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./:/app

networks:
  backend:
   external: true
